name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: mkdir ~/.ssh
      - run: echo "$SSH_PRIVATE_KEY" >> ~/.ssh/github-action
      - run: cat ~/.ssh/github-action
      - run: chmod 400 ~/.ssh/github-action
      - run: echo -e "Host static\n\tUser $SSH_USERNAME\n\tHostName $SSH_HOST\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
      - run: cat ~/.ssh/config
      - run: rsync -r build $SSH_USERNAME@$SSH_HOST:$DEPLOY_PATH
